Added initial release

diff --git a/templates/make_manifest b/templates/make_manifest
--- a/templates/make_manifest
+++ b/templates/make_manifest
@@ -2,46 +2,93 @@
 
 set -e
 
+version_checker() {
+	if [[ $1 == $2 ]]
+	then
+		return 0
+	fi
+	local IFS=.
+	local i actual=($1) expected=($2)
+	# fill empty fields in actual with zeros
+	for ((i=${#actual[@]}; i<${#expected[@]}; i++))
+	do
+		actual[i]=0
+	done
+	actual_numeric=0
+	expected_numeric=0
+	for ((i=0; i<${#actual[@]}; i++))
+	do
+		if [[ -z ${expected[i]} ]]
+		then
+			# fill empty fields in expected with zeros
+			expected[i]=0
+		fi
+		actual_numeric=$((actual_numeric+${actual[i]}*1000**(${#actual[@]}-i)))
+		expected_numeric=$((expected_numeric+${expected[i]}*1000**(${#expected[@]}-i)))
+	done
+
+
+	if [[ ${actual_numeric} -lt ${expected_numeric} ]]; then
+		return 1
+	fi
+	return 0
+}
+
+required_version="1.8.9"
+dev_version=$(spruce -v 2>&1 | perl -pe 's/.*development.*/DEV/')
+if [[ ${dev_version} == "DEV" ]]; then
+	echo "Treating 'development' version as up-to-date with spruce v${required_version}"
+else
+	spruce_version=$(spruce -v 2>&1 | perl -pe 's|.*?(\d+\.\d+(\.\d+)*).*|$1|')
+	if [[ -z ${spruce_version} || $(echo ${current_version} | egrep '[^0-9\.]') ]]; then
+		echo "make_manifest requires spruce version ${required_version} or newer, but the current version could not be parsed: ${spruce_version}"
+		exit 1
+	fi
+	if ! version_checker ${spruce_version} ${required_version}; then
+		echo "make_manifest requires spruce version ${required_version} or newer, but found version ${spruce_version}"
+		exit
+	fi
+fi
+
 template_prefix="locker"
 STEMCELL_OS=${STEMCELL_OS:-ubuntu}
 
 infrastructure=$1
 
-fail() {
-	echo >&2 $*
-}
-
-if [[ "$infrastructure" != "aws-ec2" && "$infrastructure" != "warden" ]] ; then
-  fail "usage: ./make_manifest <aws-ec2|warden>"
+if [[ "$infrastructure" != "aws-ec2" ]] && \
+    [[ "$infrastructure" != "openstack" ]] && \
+    [[ "$infrastructure" != "warden" ]]; then
+  echo >&2 "usage: ./make_manifest <aws-ec2|warden|openstack>"
   exit 1
 fi
-
-case "${infrastructure}/${STEMCELL_OS}" in
-  (warden/*)       STEMCELL_URL="https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent" ;;
-  (aws-ec2/ubuntu) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-ubuntu-trusty-go_agent" ;;
-  (aws-ec2/centos) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-centos-7-go_agent" ;;
-  (*)
-    fail "Invalid infrastructure or OS specified."
-    exit 1
-    ;;
-esac
 
 shift
 
 BOSH_STATUS=$(bosh status)
 DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')
-DIRECTOR_CPI=$(echo "$BOSH_STATUS" | grep CPI | awk '{print $2}' | sed -e 's/_cpi//')
-DIRECTOR_NAME=$(echo "$BOSH_STATUS" | grep Name | sed 's/.*Name *//')
+DIRECTOR_CPI=$(echo "$BOSH_STATUS" | grep CPI | awk '{print $2}' | sed 's/_cpi$//')
+DIRECTOR_NAME=$(echo "$BOSH_STATUS" | grep Name | awk '{print $2}')
 NAME=$template_prefix-$infrastructure
 
-if [[ $DIRECTOR_CPI = "warden" && ${infrastructure} != "warden" ]]; then
-  fail "Not targeting bosh-lite with warden CPI. Please make sure you have run 'bosh target' and are targeting a BOSH lite before running this script."
-  exit 1
+if [[ $DIRECTOR_NAME = "warden" ]]; then
+  if [[ $infrastructure != "warden" ]]; then
+    echo "Not targeting bosh-lite with warden CPI. Please use 'bosh target' before running this script."
+    exit 1
+  fi
 fi
 
-if [[ $infrastructure = "aws-ec2" && ${DIRECTOR_CPI} != "aws" ]]; then
-  fail "Not targeting an AWS BOSH. Please make sure you have run 'bosh target' and are targeting an AWS BOSH before running this script."
-  exit 1
+if [[ $infrastructure = "aws-ec2" ]]; then
+  if [[ $DIRECTOR_CPI != "aws" ]]; then
+    echo "Not targeting an AWS BOSH. Please use 'bosh target' before running this script."
+    exit 1
+  fi
+fi
+
+if [[ $infrastructure = "openstack" ]]; then
+  if [[ $DIRECTOR_CPI != "openstack" ]]; then
+    echo "Not targeting an OpenStack BOSH. Please use 'bosh target' before running this script."
+    exit 1
+  fi
 fi
 
 function latest_uploaded_stemcell {
@@ -49,10 +96,10 @@ function latest_uploaded_stemcell {
 }
 
 STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
-if [[ -z ${STEMCELL} ]]; then
+if [[ "${STEMCELL}X" == "X" ]]; then
   echo
   echo "Uploading latest $DIRECTOR_CPI/$STEMCELL_OS stemcell..."
-  echo " (from ${STEMCELL_URL})"
+  STEMCELL_URL=$(bosh public stemcells --full | grep $DIRECTOR_CPI | grep $STEMCELL_OS | sort -nr | head -n1 | awk '{ print $4 }')
   bosh upload stemcell $STEMCELL_URL
 fi
 STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
@@ -62,20 +109,32 @@ release=$templates/..
 tmpdir=$release/tmp
 
 mkdir -p $tmpdir
-cp $templates/stub.yml $tmpdir/stub-with-uuid.yml
-echo $DIRECTOR_NAME $DIRECTOR_CPI $DIRECTOR_UUID $STEMCELL
-perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" $tmpdir/stub-with-uuid.yml
-perl -pi -e "s/NAME/$NAME/g" $tmpdir/stub-with-uuid.yml
-perl -pi -e "s/STEMCELL/$STEMCELL/g" $tmpdir/stub-with-uuid.yml
+cat <<EOF > $tmpdir/stub-with-uuid.yml
+---
+name: ${NAME}
+director_uuid: ${DIRECTOR_UUID}
+EOF
 
-if ! [ -x "$(command -v spruce)" ]; then
-  echo 'spruce is not installed. Please download at https://github.com/geofffranks/spruce/releases' >&2
+
+if [[ $(bosh cloud-config | spruce json | jq -r '.networks[] | select(.name == "locker") | .name') != "locker" ]]; then
+	echo >&2 "Your cloud-config does not have the 'locker' network in it. See templates/cloud-config-warden.yml for an example."
+	exit 1
+fi
+if [[ $(bosh cloud-config | spruce json | jq -r '.vm_types[] | select(.name == "small") | .name') != "small" ]]; then
+	echo >&2 "Your cloud-config does not have the 'small' vm_type in it. See templates/cloud-config-warden.yml for an example."
+	exit 1
 fi
 
-spruce merge --prune meta \
-  $templates/deployment.yml \
-  $templates/jobs.yml \
-  $templates/infrastructure-${infrastructure}.yml \
+bosh cloud-config | spruce merge --cherry-pick networks > $tmpdir/cc-networks.yml
+
+if [[ -n "${KEEPALIVED_VIP}" ]]; then
+	keepalived=$templates/keepalived.yml
+fi
+
+spruce merge --prune networks \
+  $templates/locker.yml \
+  $keepalived \
+  $tmpdir/cc-networks.yml \
   $tmpdir/stub-with-uuid.yml \
   $* > $tmpdir/$NAME-manifest.yml
 
